### PR TITLE
Fix comparison

### PR DESCRIPTION
**Pull request by twoRoger**
before:
```
               mean time ops/sec
Q              6.104ms   164
When           2.110ms   474
Bluebird       2.405ms   416
Pinkie         5.646ms   177
ES2015 Promise 5.667ms   176
Vow            2.090ms   478
```

after:
```
               mean time ops/sec
Q              6.194ms   161
When           2.092ms   478
Bluebird       2.491ms   401
Pinkie         5.606ms   178
ES2015 Promise 5.830ms   172
Vow            2.504ms   399
```

`"Fix" benchmark` commit(https://github.com/dfilatov/vow/commit/013ab8b1e37c24a77aa59ff2dabcd425cae53efe) looks suspicious... ;)
suspicious

### CODE REVIEW

**Comment by zxqfox** [comment]
nice catch! ;-)

**Comment by dfilatov** [comment]
@twoRoger :+1:

**Comment by dfilatov** [comment]
But with my laptop and nodejs 4.2.1 I've got quite different result:
```
               mean time ops/sec
Q              5.282ms   189
When           1.881ms   532
Bluebird       2.137ms   468
Pinkie         2.936ms   341
ES2015 Promise 2.915ms   343
Vow            1.861ms   537
```

**Comment by awinogradov** [comment]
Wtf this https://github.com/petkaantonov/bluebird/tree/master/benchmark ?

**Pull request merged**
